# Manipulation de données avec NumPy

In [2]:
#Importation de NumPy

import numpy as np   # as permet de renommer la bibliothèque

In [5]:
# Les vecteurs

vect= np.array(range(1, 50,5))
vect

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [6]:
#connaître les dimensions 
vect.shape 

(10,)

In [8]:
#Ajout de valeur

vect= np.append(vect,[51, 70] )
vect

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 70, 51, 70])

In [9]:
#Les Matrices

mat=np.array([[3,5,0],[1,8,4]])
mat

array([[3, 5, 0],
       [1, 8, 4]])

# Opérations

In [14]:
x=np.array([[3,5,0],[1,8,4]])
y=np.array([[4,1,2],[0,3,7]])

#addition 
add_x_y= x+y #
sub_x_y=x-y  #
mult_x_y= x*y #
#div_x_y = x/y

# Selection d'un élément ou de sous ensemble

In [19]:
a=x[1,2]
a2=x[0] #récupere la première ligne
a2


array([3, 5, 0])

In [21]:
b=y[:,0] #selectionnne la premiere colone
b

array([4, 0])

In [22]:
c= x[1:,0:2]
c


array([[1, 8]])